jobs:
- job: fabric_macos_pr
  pool:
    name: Hosted Mac Internal Mojave
    demands: ['xcode', 'sh', 'npm']
  displayName: Fabric macOS PR
  timeoutInMinutes: 60 # how long to run the job before automatically cancelling
  cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them
  steps:
  - template: xcode-build.yml
    parameters:
      xcode_actions: 'build'
      xcode_scheme: 'OfficeUIFabric'
      xcode_configuration: 'Debug'
  
  - template: xcode-build.yml
    parameters:
      xcode_actions: 'build'
      xcode_scheme: 'OfficeUIFabric'
      xcode_configuration: 'Release'
    
  - template: xcode-build.yml
    parameters:
      xcode_actions: 'build test'
      xcode_scheme: 'OfficeUIFabricTestApp'
      xcode_configuration: 'Debug'
      xcode_displayNameTags: '[test] [security-analysis]'

  - template: xcode-build.yml
    parameters:
      xcode_actions: 'build test'
      xcode_scheme: 'OfficeUIFabricTestApp'
      xcode_configuration: 'Release'
      xcode_displayNameTags: '[test] [security-analysis]'
