jobs:
- job: fabric_macos_publish_nuget
  pool:
    name: Hosted Mac Internal Mojave
    demands: ['xcode', 'sh', 'npm']
  displayName: Fabric macOS Publish NuGet
  timeoutInMinutes: 60 # how long to run the job before automatically cancelling
  cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them
  steps:

  # Install NuGet v4.6.4+
  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: '>=4.6.4'

  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false

  - template: xcode-build.yml
    parameters:
      xcode_actions: 'build'
      xcode_scheme: 'OfficeUIFabric'
      xcode_configuration: 'Debug'
      xcode_extraArgs: 'OTHER_SWIFT_FLAGS=-gline-tables-only CLANG_DEBUG_INFORMATION_LEVEL=line-tables-only BUILD_LIBRARY_FOR_DISTRIBUTION=YES'
  
  - template: xcode-build.yml
    parameters:
      xcode_actions: 'build'
      xcode_scheme: 'OfficeUIFabric'
      xcode_configuration: 'Release'
      xcode_extraArgs: 'OTHER_SWIFT_FLAGS=-gline-tables-only CLANG_DEBUG_INFORMATION_LEVEL=line-tables-only BUILD_LIBRARY_FOR_DISTRIBUTION=YES'

  - bash: 'scripts/prepare_for_nuget_pack.sh'
    displayName: 'Zip frameworks to preserve symlinks'

  # generate the nuspecsToPack and sanitizedBuildNumber environment variables

  - script: 'node scripts/vsto-collect-nuspec.js apple'
    displayName: 'Generate versioned nuspec files'

  # pack all the nuspecs

  - task: NuGetCommand@2
    displayName: 'NuGet pack'
    inputs:
      command: pack
      packagesToPack: '$(nuspecsToPack)'
      buildProperties: buildNumber=$(sanitizedBuildNumber);commitId=$(Build.SourceVersion);repoUri=$(Build.Repository.Uri)

  # push packages

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: OfficeUIFabricmacOSNuPkg'
    inputs:
      ArtifactName: OfficeUIFabricmacOSNuPkg
    condition: succeededOrFailed()
