name: CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Running CI
      run: scripts/ci.sh
