name: CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  xcodebuild:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        build_command: [
          'macos_build OfficeUIFabricTestApp Debug build test',
          'macos_build OfficeUIFabricTestApp Release build test',
          'ios_simulator_build OfficeUIFabric Debug build test',
          'ios_simulator_build OfficeUIFabric Release build',
          'ios_simulator_build Demo.Development Debug build',
          'ios_simulator_build Demo.Development Release build',
          'ios_device_build Demo.Development Debug build',
          'ios_device_build Demo.Development Release build',
        ]

    steps:
    - uses: actions/checkout@v2
    - name: Switch to Xcode 11.2.1
      run: sudo xcode-select --switch /Applications/Xcode_11.2.1.app/Contents/Developer
    - name: scripts/xcodebuild_wrapper.sh ${{ matrix.build_command }}
      run: scripts/xcodebuild_wrapper.sh ${{ matrix.build_command }}
